import { BuildingCatalog, BuildingData, BuildingEnum } from "../types";

export const BUILDING_CATALOG: BuildingCatalog = {
  [BuildingEnum.FARM]: {
    cost: { food: 100, wood: 50 },
    incomeBonus: { food: 5 },
    upgradeMultiplier: 1.5,
    buildTime: 0,
    displayName: "Farm",
    type: "farm",
    level: 1,
    upgradeCost: { food: 50, wood: 50 },
  },
  [BuildingEnum.LUMBER_MILL]: {
    cost: { wood: 100 },
    incomeBonus: { wood: 5 },
    upgradeMultiplier: 1.4,
    buildTime: 0,
    displayName: "Lumber Mill",
    type: "farm",
    level: 1,
    upgradeCost: { wood: 50 },
  },
  [BuildingEnum.BARRACKS]: {
    cost: { food: 100 },
    incomeBonus: { wood: 5 },
    upgradeMultiplier: 1.4,
    buildTime: 0,
    displayName: "Barracks",
    type: "barracks",
    level: 1,
    upgradeCost: { food: 500 },
  },
  [BuildingEnum.MINE]: {
    cost: { gold: 50, stone: 100 },
    incomeBonus: { gold: 2, stone: 10 },
    upgradeMultiplier: 1.4,
    buildTime: 0,
    displayName: "Mine",
    type: "farm",
    level: 1,
    upgradeCost: { gold: 500, stone: 1000 },
  },
  [BuildingEnum.RESEARCH]: {
    cost: { wood: 100, food: 100, gold: 10, stone: 100 },
    incomeBonus: { wood: 5 },
    upgradeMultiplier: 1.4,
    buildTime: 0,
    displayName: "Research",
    type: "research",
    level: 1,
    upgradeCost: { food: 50, wood: 50 },
  },
};
